//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 04:13:53 PM EST 
//


package com.ups.ttg.bsis.shipment.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ups.ttg.bsis.shipment.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Shipments_QNAME = new QName("", "Shipments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ups.ttg.bsis.shipment.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentsType }
     * 
     */
    public ShipmentsType createShipmentsType() {
        return new ShipmentsType();
    }

    /**
     * Create an instance of {@link ShipmentType }
     * 
     */
    public ShipmentType createShipmentType() {
        return new ShipmentType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link ImportCountryType }
     * 
     */
    public ImportCountryType createImportCountryType() {
        return new ImportCountryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShipmentsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Shipments")
    public JAXBElement<ShipmentsType> createShipments(ShipmentsType value) {
        return new JAXBElement<ShipmentsType>(_Shipments_QNAME, ShipmentsType.class, null, value);
    }

}
