//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 04:13:53 PM EST 
//


package com.ups.ttg.bsis.shipment.model;

import java.io.ByteArrayInputStream;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ShipmentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Shipment" type="{}ShipmentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentsType", propOrder = {
    "shipment"
})
@XmlRootElement(name = "Shipments")
public class ShipmentsType {

    @XmlElement(name = "Shipment")
    protected List<ShipmentType> shipment;

    public ShipmentsType() { }
    
    /**
     * 
     * @param shipment
     */
    public ShipmentsType(ShipmentType shipment) {
		super();
		getShipment().add(shipment);
	}
    
    /**
     * 
     * @param shipment
     */
    public ShipmentsType(List<ShipmentType> shipment) {
		super();
		this.shipment = shipment;
	}
    
    /**
     * 
     * @param str
     * @return
     * @throws JAXBException
     */
    public static ShipmentsType getAsObject(String str) throws JAXBException {
    	try {
	  		JAXBContext jc = JAXBContext.newInstance(new Class[]{com.ups.ttg.bsis.shipment.model.ShipmentsType.class});
	  		Unmarshaller unmarshaller = jc.createUnmarshaller();

  			return (ShipmentsType) unmarshaller.unmarshal(new ByteArrayInputStream(str.trim().getBytes()));
    	}
    	catch (Exception e) {
    		e.printStackTrace();
    		return null;
    	}
  	}
    
    /**
     * 
     * @param body
     * @return
     * @throws JAXBException
     */
    public static String getAsXml(ShipmentsType body) throws JAXBException {
  		JAXBContext jc = JAXBContext.newInstance(new Class[]{com.ups.ttg.bsis.shipment.model.ShipmentsType.class});
  		Marshaller marshaller = jc.createMarshaller();
  		marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, false);
  		StringWriter sw = new StringWriter();
  		marshaller.marshal(body, sw);
  		jc = null;
  		
  		return sw.toString();
  	}
    
    /**
     * 
     * @return
     * @throws JAXBException
     */
    public String getAsXml() throws JAXBException {
		JAXBContext jc = JAXBContext.newInstance(new Class[]{com.ups.ttg.bsis.shipment.model.ShipmentsType.class});
		Marshaller marshaller = jc.createMarshaller();
		marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, false);
		StringWriter sw = new StringWriter();
		marshaller.marshal(this, sw);
		jc = null;
		
		return sw.toString();
	}

	/**
     * Gets the value of the shipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShipmentType }
     * 
     * 
     */
    public List<ShipmentType> getShipment() {
        if (shipment == null) {
            shipment = new ArrayList<ShipmentType>();
        }
        return this.shipment;
    }
    
    public void addShipment(ShipmentType shipment) {
    	getShipment().add(shipment);
    }

}
